// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mesh.proto

#include "stdafx.h"

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#ifdef _MSC_VER
#  pragma warning(push)
#  pragma warning(disable: 4127 4244 4267)
#endif
#include "Mesh.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* Triangle_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Triangle_reflection_ = NULL;
const ::google::protobuf::Descriptor* Mesh_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Mesh_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Mesh_2eproto() {
  protobuf_AddDesc_Mesh_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Mesh.proto");
  GOOGLE_CHECK(file != NULL);
  Triangle_descriptor_ = file->message_type(0);
  static const int Triangle_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Triangle, vert1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Triangle, vert2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Triangle, vert3_),
  };
  Triangle_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Triangle_descriptor_,
      Triangle::default_instance_,
      Triangle_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Triangle, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Triangle, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Triangle));
  Mesh_descriptor_ = file->message_type(1);
  static const int Mesh_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, material_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, textures_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, vertices_format_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, vertices_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, skeleton_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, triangles_),
  };
  Mesh_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Mesh_descriptor_,
      Mesh::default_instance_,
      Mesh_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Mesh, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Mesh));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Mesh_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Triangle_descriptor_, &Triangle::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Mesh_descriptor_, &Mesh::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Mesh_2eproto() {
  delete Triangle::default_instance_;
  delete Triangle_reflection_;
  delete Mesh::default_instance_;
  delete Mesh_reflection_;
}

void protobuf_AddDesc_Mesh_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf::protobuf_AddDesc_VertexDeclaration_2eproto();
  ::protobuf::protobuf_AddDesc_Skeleton_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nMesh.proto\022\010protobuf\032\027VertexDeclaratio"
    "n.proto\032\016Skeleton.proto\"7\n\010Triangle\022\r\n\005v"
    "ert1\030\001 \002(\r\022\r\n\005vert2\030\002 \002(\r\022\r\n\005vert3\030\003 \002(\r"
    "\"\301\001\n\004Mesh\022\020\n\010material\030\001 \002(\t\022\020\n\010textures\030"
    "\002 \003(\t\0224\n\017vertices_format\030\003 \002(\0132\033.protobu"
    "f.VertexDeclaration\022\025\n\rvertices_data\030\004 \002"
    "(\014\022!\n\010skeleton\030\005 \002(\0132\017.protobuf.Joint\022%\n"
    "\ttriangles\030\006 \003(\0132\022.protobuf.Triangle", 316);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Mesh.proto", &protobuf_RegisterTypes);
  Triangle::default_instance_ = new Triangle();
  Mesh::default_instance_ = new Mesh();
  Triangle::default_instance_->InitAsDefaultInstance();
  Mesh::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Mesh_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Mesh_2eproto {
  StaticDescriptorInitializer_Mesh_2eproto() {
    protobuf_AddDesc_Mesh_2eproto();
  }
} static_descriptor_initializer_Mesh_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Triangle::kVert1FieldNumber;
const int Triangle::kVert2FieldNumber;
const int Triangle::kVert3FieldNumber;
#endif  // !_MSC_VER

Triangle::Triangle()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Triangle::InitAsDefaultInstance() {
}

Triangle::Triangle(const Triangle& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Triangle::SharedCtor() {
  _cached_size_ = 0;
  vert1_ = 0u;
  vert2_ = 0u;
  vert3_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Triangle::~Triangle() {
  SharedDtor();
}

void Triangle::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Triangle::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Triangle::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Triangle_descriptor_;
}

const Triangle& Triangle::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Mesh_2eproto();
  return *default_instance_;
}

Triangle* Triangle::default_instance_ = NULL;

Triangle* Triangle::New() const {
  return new Triangle;
}

void Triangle::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    vert1_ = 0u;
    vert2_ = 0u;
    vert3_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Triangle::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 vert1 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &vert1_)));
          set_has_vert1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_vert2;
        break;
      }

      // required uint32 vert2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vert2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &vert2_)));
          set_has_vert2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_vert3;
        break;
      }

      // required uint32 vert3 = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_vert3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &vert3_)));
          set_has_vert3();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Triangle::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 vert1 = 1;
  if (has_vert1()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->vert1(), output);
  }

  // required uint32 vert2 = 2;
  if (has_vert2()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->vert2(), output);
  }

  // required uint32 vert3 = 3;
  if (has_vert3()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->vert3(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Triangle::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 vert1 = 1;
  if (has_vert1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->vert1(), target);
  }

  // required uint32 vert2 = 2;
  if (has_vert2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->vert2(), target);
  }

  // required uint32 vert3 = 3;
  if (has_vert3()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->vert3(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Triangle::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 vert1 = 1;
    if (has_vert1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->vert1());
    }

    // required uint32 vert2 = 2;
    if (has_vert2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->vert2());
    }

    // required uint32 vert3 = 3;
    if (has_vert3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->vert3());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Triangle::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Triangle* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Triangle*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Triangle::MergeFrom(const Triangle& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_vert1()) {
      set_vert1(from.vert1());
    }
    if (from.has_vert2()) {
      set_vert2(from.vert2());
    }
    if (from.has_vert3()) {
      set_vert3(from.vert3());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Triangle::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Triangle::CopyFrom(const Triangle& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Triangle::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void Triangle::Swap(Triangle* other) {
  if (other != this) {
    std::swap(vert1_, other->vert1_);
    std::swap(vert2_, other->vert2_);
    std::swap(vert3_, other->vert3_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Triangle::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Triangle_descriptor_;
  metadata.reflection = Triangle_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Mesh::kMaterialFieldNumber;
const int Mesh::kTexturesFieldNumber;
const int Mesh::kVerticesFormatFieldNumber;
const int Mesh::kVerticesDataFieldNumber;
const int Mesh::kSkeletonFieldNumber;
const int Mesh::kTrianglesFieldNumber;
#endif  // !_MSC_VER

Mesh::Mesh()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Mesh::InitAsDefaultInstance() {
  vertices_format_ = const_cast< ::protobuf::VertexDeclaration*>(&::protobuf::VertexDeclaration::default_instance());
  skeleton_ = const_cast< ::protobuf::Joint*>(&::protobuf::Joint::default_instance());
}

Mesh::Mesh(const Mesh& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Mesh::SharedCtor() {
  _cached_size_ = 0;
  material_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  vertices_format_ = NULL;
  vertices_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  skeleton_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Mesh::~Mesh() {
  SharedDtor();
}

void Mesh::SharedDtor() {
  if (material_ != &::google::protobuf::internal::kEmptyString) {
    delete material_;
  }
  if (vertices_data_ != &::google::protobuf::internal::kEmptyString) {
    delete vertices_data_;
  }
  if (this != default_instance_) {
    delete vertices_format_;
    delete skeleton_;
  }
}

void Mesh::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Mesh::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Mesh_descriptor_;
}

const Mesh& Mesh::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Mesh_2eproto();
  return *default_instance_;
}

Mesh* Mesh::default_instance_ = NULL;

Mesh* Mesh::New() const {
  return new Mesh;
}

void Mesh::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_material()) {
      if (material_ != &::google::protobuf::internal::kEmptyString) {
        material_->clear();
      }
    }
    if (has_vertices_format()) {
      if (vertices_format_ != NULL) vertices_format_->::protobuf::VertexDeclaration::Clear();
    }
    if (has_vertices_data()) {
      if (vertices_data_ != &::google::protobuf::internal::kEmptyString) {
        vertices_data_->clear();
      }
    }
    if (has_skeleton()) {
      if (skeleton_ != NULL) skeleton_->::protobuf::Joint::Clear();
    }
  }
  textures_.Clear();
  triangles_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Mesh::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string material = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_material()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->material().data(), this->material().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_textures;
        break;
      }

      // repeated string textures = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_textures:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_textures()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->textures(this->textures_size() - 1).data(),
            this->textures(this->textures_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_textures;
        if (input->ExpectTag(26)) goto parse_vertices_format;
        break;
      }

      // required .protobuf.VertexDeclaration vertices_format = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_vertices_format:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_vertices_format()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_vertices_data;
        break;
      }

      // required bytes vertices_data = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_vertices_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_vertices_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_skeleton;
        break;
      }

      // required .protobuf.Joint skeleton = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_skeleton:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_skeleton()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_triangles;
        break;
      }

      // repeated .protobuf.Triangle triangles = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_triangles:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_triangles()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_triangles;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Mesh::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string material = 1;
  if (has_material()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->material().data(), this->material().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->material(), output);
  }

  // repeated string textures = 2;
  for (int i = 0; i < this->textures_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->textures(i).data(), this->textures(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->textures(i), output);
  }

  // required .protobuf.VertexDeclaration vertices_format = 3;
  if (has_vertices_format()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->vertices_format(), output);
  }

  // required bytes vertices_data = 4;
  if (has_vertices_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      4, this->vertices_data(), output);
  }

  // required .protobuf.Joint skeleton = 5;
  if (has_skeleton()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->skeleton(), output);
  }

  // repeated .protobuf.Triangle triangles = 6;
  for (int i = 0; i < this->triangles_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->triangles(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Mesh::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string material = 1;
  if (has_material()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->material().data(), this->material().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->material(), target);
  }

  // repeated string textures = 2;
  for (int i = 0; i < this->textures_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->textures(i).data(), this->textures(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->textures(i), target);
  }

  // required .protobuf.VertexDeclaration vertices_format = 3;
  if (has_vertices_format()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->vertices_format(), target);
  }

  // required bytes vertices_data = 4;
  if (has_vertices_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->vertices_data(), target);
  }

  // required .protobuf.Joint skeleton = 5;
  if (has_skeleton()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->skeleton(), target);
  }

  // repeated .protobuf.Triangle triangles = 6;
  for (int i = 0; i < this->triangles_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->triangles(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Mesh::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string material = 1;
    if (has_material()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->material());
    }

    // required .protobuf.VertexDeclaration vertices_format = 3;
    if (has_vertices_format()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->vertices_format());
    }

    // required bytes vertices_data = 4;
    if (has_vertices_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->vertices_data());
    }

    // required .protobuf.Joint skeleton = 5;
    if (has_skeleton()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->skeleton());
    }

  }
  // repeated string textures = 2;
  total_size += 1 * this->textures_size();
  for (int i = 0; i < this->textures_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->textures(i));
  }

  // repeated .protobuf.Triangle triangles = 6;
  total_size += 1 * this->triangles_size();
  for (int i = 0; i < this->triangles_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->triangles(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Mesh::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Mesh* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Mesh*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Mesh::MergeFrom(const Mesh& from) {
  GOOGLE_CHECK_NE(&from, this);
  textures_.MergeFrom(from.textures_);
  triangles_.MergeFrom(from.triangles_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_material()) {
      set_material(from.material());
    }
    if (from.has_vertices_format()) {
      mutable_vertices_format()->::protobuf::VertexDeclaration::MergeFrom(from.vertices_format());
    }
    if (from.has_vertices_data()) {
      set_vertices_data(from.vertices_data());
    }
    if (from.has_skeleton()) {
      mutable_skeleton()->::protobuf::Joint::MergeFrom(from.skeleton());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Mesh::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Mesh::CopyFrom(const Mesh& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Mesh::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001d) != 0x0000001d) return false;

  if (has_vertices_format()) {
    if (!this->vertices_format().IsInitialized()) return false;
  }
  for (int i = 0; i < triangles_size(); i++) {
    if (!this->triangles(i).IsInitialized()) return false;
  }
  return true;
}

void Mesh::Swap(Mesh* other) {
  if (other != this) {
    std::swap(material_, other->material_);
    textures_.Swap(&other->textures_);
    std::swap(vertices_format_, other->vertices_format_);
    std::swap(vertices_data_, other->vertices_data_);
    std::swap(skeleton_, other->skeleton_);
    triangles_.Swap(&other->triangles_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Mesh::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Mesh_descriptor_;
  metadata.reflection = Mesh_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)
#ifdef _MSC_VER
#  pragma warning(pop)
#endif
