// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShaderProgram.proto

#ifndef PROTOBUF_ShaderProgram_2eproto__INCLUDED
#define PROTOBUF_ShaderProgram_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ShaderProgram_2eproto();
void protobuf_AssignDesc_ShaderProgram_2eproto();
void protobuf_ShutdownFile_ShaderProgram_2eproto();

class ShaderParam;
class ShaderParamBlock;
class ShaderProgram;
class ShaderProgram_Shader;

enum ShaderProgram_ShaderType {
  ShaderProgram_ShaderType_COMPUTE_SHADER = 1,
  ShaderProgram_ShaderType_VERTEX_SHADER = 2,
  ShaderProgram_ShaderType_TESS_CONTROL_SHADER = 3,
  ShaderProgram_ShaderType_TESS_EVALUATION_SHADER = 4,
  ShaderProgram_ShaderType_GEOMETRY_SHADER = 5,
  ShaderProgram_ShaderType_FRAGMENT_SHADER = 6
};
bool ShaderProgram_ShaderType_IsValid(int value);
const ShaderProgram_ShaderType ShaderProgram_ShaderType_ShaderType_MIN = ShaderProgram_ShaderType_COMPUTE_SHADER;
const ShaderProgram_ShaderType ShaderProgram_ShaderType_ShaderType_MAX = ShaderProgram_ShaderType_FRAGMENT_SHADER;
const int ShaderProgram_ShaderType_ShaderType_ARRAYSIZE = ShaderProgram_ShaderType_ShaderType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ShaderProgram_ShaderType_descriptor();
inline const ::std::string& ShaderProgram_ShaderType_Name(ShaderProgram_ShaderType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ShaderProgram_ShaderType_descriptor(), value);
}
inline bool ShaderProgram_ShaderType_Parse(
    const ::std::string& name, ShaderProgram_ShaderType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ShaderProgram_ShaderType>(
    ShaderProgram_ShaderType_descriptor(), name, value);
}
// ===================================================================

class ShaderParam : public ::google::protobuf::Message {
 public:
  ShaderParam();
  virtual ~ShaderParam();

  ShaderParam(const ShaderParam& from);

  inline ShaderParam& operator=(const ShaderParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShaderParam& default_instance();

  void Swap(ShaderParam* other);

  // implements Message ----------------------------------------------

  ShaderParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ShaderParam& from);
  void MergeFrom(const ShaderParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string uniform_name = 1;
  inline bool has_uniform_name() const;
  inline void clear_uniform_name();
  static const int kUniformNameFieldNumber = 1;
  inline const ::std::string& uniform_name() const;
  inline void set_uniform_name(const ::std::string& value);
  inline void set_uniform_name(const char* value);
  inline void set_uniform_name(const char* value, size_t size);
  inline ::std::string* mutable_uniform_name();
  inline ::std::string* release_uniform_name();
  inline void set_allocated_uniform_name(::std::string* uniform_name);

  // required string value = 2;
  inline bool has_value() const;
  inline void clear_value();
  static const int kValueFieldNumber = 2;
  inline const ::std::string& value() const;
  inline void set_value(const ::std::string& value);
  inline void set_value(const char* value);
  inline void set_value(const char* value, size_t size);
  inline ::std::string* mutable_value();
  inline ::std::string* release_value();
  inline void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:protobuf.ShaderParam)
 private:
  inline void set_has_uniform_name();
  inline void clear_has_uniform_name();
  inline void set_has_value();
  inline void clear_has_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* uniform_name_;
  ::std::string* value_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_ShaderProgram_2eproto();
  friend void protobuf_AssignDesc_ShaderProgram_2eproto();
  friend void protobuf_ShutdownFile_ShaderProgram_2eproto();

  void InitAsDefaultInstance();
  static ShaderParam* default_instance_;
};
// -------------------------------------------------------------------

class ShaderParamBlock : public ::google::protobuf::Message {
 public:
  ShaderParamBlock();
  virtual ~ShaderParamBlock();

  ShaderParamBlock(const ShaderParamBlock& from);

  inline ShaderParamBlock& operator=(const ShaderParamBlock& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShaderParamBlock& default_instance();

  void Swap(ShaderParamBlock* other);

  // implements Message ----------------------------------------------

  ShaderParamBlock* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ShaderParamBlock& from);
  void MergeFrom(const ShaderParamBlock& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .protobuf.ShaderParam params = 1;
  inline int params_size() const;
  inline void clear_params();
  static const int kParamsFieldNumber = 1;
  inline const ::protobuf::ShaderParam& params(int index) const;
  inline ::protobuf::ShaderParam* mutable_params(int index);
  inline ::protobuf::ShaderParam* add_params();
  inline const ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderParam >&
      params() const;
  inline ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderParam >*
      mutable_params();

  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:protobuf.ShaderParamBlock)
 private:
  inline void set_has_name();
  inline void clear_has_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderParam > params_;
  ::std::string* name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_ShaderProgram_2eproto();
  friend void protobuf_AssignDesc_ShaderProgram_2eproto();
  friend void protobuf_ShutdownFile_ShaderProgram_2eproto();

  void InitAsDefaultInstance();
  static ShaderParamBlock* default_instance_;
};
// -------------------------------------------------------------------

class ShaderProgram_Shader : public ::google::protobuf::Message {
 public:
  ShaderProgram_Shader();
  virtual ~ShaderProgram_Shader();

  ShaderProgram_Shader(const ShaderProgram_Shader& from);

  inline ShaderProgram_Shader& operator=(const ShaderProgram_Shader& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShaderProgram_Shader& default_instance();

  void Swap(ShaderProgram_Shader* other);

  // implements Message ----------------------------------------------

  ShaderProgram_Shader* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ShaderProgram_Shader& from);
  void MergeFrom(const ShaderProgram_Shader& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .protobuf.ShaderProgram.ShaderType type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::protobuf::ShaderProgram_ShaderType type() const;
  inline void set_type(::protobuf::ShaderProgram_ShaderType value);

  // required string filename = 2;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFilenameFieldNumber = 2;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  inline void set_allocated_filename(::std::string* filename);

  // @@protoc_insertion_point(class_scope:protobuf.ShaderProgram.Shader)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_filename();
  inline void clear_has_filename();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* filename_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_ShaderProgram_2eproto();
  friend void protobuf_AssignDesc_ShaderProgram_2eproto();
  friend void protobuf_ShutdownFile_ShaderProgram_2eproto();

  void InitAsDefaultInstance();
  static ShaderProgram_Shader* default_instance_;
};
// -------------------------------------------------------------------

class ShaderProgram : public ::google::protobuf::Message {
 public:
  ShaderProgram();
  virtual ~ShaderProgram();

  ShaderProgram(const ShaderProgram& from);

  inline ShaderProgram& operator=(const ShaderProgram& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShaderProgram& default_instance();

  void Swap(ShaderProgram* other);

  // implements Message ----------------------------------------------

  ShaderProgram* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ShaderProgram& from);
  void MergeFrom(const ShaderProgram& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ShaderProgram_Shader Shader;

  typedef ShaderProgram_ShaderType ShaderType;
  static const ShaderType COMPUTE_SHADER = ShaderProgram_ShaderType_COMPUTE_SHADER;
  static const ShaderType VERTEX_SHADER = ShaderProgram_ShaderType_VERTEX_SHADER;
  static const ShaderType TESS_CONTROL_SHADER = ShaderProgram_ShaderType_TESS_CONTROL_SHADER;
  static const ShaderType TESS_EVALUATION_SHADER = ShaderProgram_ShaderType_TESS_EVALUATION_SHADER;
  static const ShaderType GEOMETRY_SHADER = ShaderProgram_ShaderType_GEOMETRY_SHADER;
  static const ShaderType FRAGMENT_SHADER = ShaderProgram_ShaderType_FRAGMENT_SHADER;
  static inline bool ShaderType_IsValid(int value) {
    return ShaderProgram_ShaderType_IsValid(value);
  }
  static const ShaderType ShaderType_MIN =
    ShaderProgram_ShaderType_ShaderType_MIN;
  static const ShaderType ShaderType_MAX =
    ShaderProgram_ShaderType_ShaderType_MAX;
  static const int ShaderType_ARRAYSIZE =
    ShaderProgram_ShaderType_ShaderType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ShaderType_descriptor() {
    return ShaderProgram_ShaderType_descriptor();
  }
  static inline const ::std::string& ShaderType_Name(ShaderType value) {
    return ShaderProgram_ShaderType_Name(value);
  }
  static inline bool ShaderType_Parse(const ::std::string& name,
      ShaderType* value) {
    return ShaderProgram_ShaderType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .protobuf.ShaderProgram.Shader shaders = 1;
  inline int shaders_size() const;
  inline void clear_shaders();
  static const int kShadersFieldNumber = 1;
  inline const ::protobuf::ShaderProgram_Shader& shaders(int index) const;
  inline ::protobuf::ShaderProgram_Shader* mutable_shaders(int index);
  inline ::protobuf::ShaderProgram_Shader* add_shaders();
  inline const ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderProgram_Shader >&
      shaders() const;
  inline ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderProgram_Shader >*
      mutable_shaders();

  // @@protoc_insertion_point(class_scope:protobuf.ShaderProgram)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderProgram_Shader > shaders_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ShaderProgram_2eproto();
  friend void protobuf_AssignDesc_ShaderProgram_2eproto();
  friend void protobuf_ShutdownFile_ShaderProgram_2eproto();

  void InitAsDefaultInstance();
  static ShaderProgram* default_instance_;
};
// ===================================================================


// ===================================================================

// ShaderParam

// required string uniform_name = 1;
inline bool ShaderParam::has_uniform_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ShaderParam::set_has_uniform_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ShaderParam::clear_has_uniform_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ShaderParam::clear_uniform_name() {
  if (uniform_name_ != &::google::protobuf::internal::kEmptyString) {
    uniform_name_->clear();
  }
  clear_has_uniform_name();
}
inline const ::std::string& ShaderParam::uniform_name() const {
  return *uniform_name_;
}
inline void ShaderParam::set_uniform_name(const ::std::string& value) {
  set_has_uniform_name();
  if (uniform_name_ == &::google::protobuf::internal::kEmptyString) {
    uniform_name_ = new ::std::string;
  }
  uniform_name_->assign(value);
}
inline void ShaderParam::set_uniform_name(const char* value) {
  set_has_uniform_name();
  if (uniform_name_ == &::google::protobuf::internal::kEmptyString) {
    uniform_name_ = new ::std::string;
  }
  uniform_name_->assign(value);
}
inline void ShaderParam::set_uniform_name(const char* value, size_t size) {
  set_has_uniform_name();
  if (uniform_name_ == &::google::protobuf::internal::kEmptyString) {
    uniform_name_ = new ::std::string;
  }
  uniform_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShaderParam::mutable_uniform_name() {
  set_has_uniform_name();
  if (uniform_name_ == &::google::protobuf::internal::kEmptyString) {
    uniform_name_ = new ::std::string;
  }
  return uniform_name_;
}
inline ::std::string* ShaderParam::release_uniform_name() {
  clear_has_uniform_name();
  if (uniform_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = uniform_name_;
    uniform_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShaderParam::set_allocated_uniform_name(::std::string* uniform_name) {
  if (uniform_name_ != &::google::protobuf::internal::kEmptyString) {
    delete uniform_name_;
  }
  if (uniform_name) {
    set_has_uniform_name();
    uniform_name_ = uniform_name;
  } else {
    clear_has_uniform_name();
    uniform_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string value = 2;
inline bool ShaderParam::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShaderParam::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShaderParam::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShaderParam::clear_value() {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    value_->clear();
  }
  clear_has_value();
}
inline const ::std::string& ShaderParam::value() const {
  return *value_;
}
inline void ShaderParam::set_value(const ::std::string& value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void ShaderParam::set_value(const char* value) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(value);
}
inline void ShaderParam::set_value(const char* value, size_t size) {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  value_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShaderParam::mutable_value() {
  set_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    value_ = new ::std::string;
  }
  return value_;
}
inline ::std::string* ShaderParam::release_value() {
  clear_has_value();
  if (value_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = value_;
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShaderParam::set_allocated_value(::std::string* value) {
  if (value_ != &::google::protobuf::internal::kEmptyString) {
    delete value_;
  }
  if (value) {
    set_has_value();
    value_ = value;
  } else {
    clear_has_value();
    value_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ShaderParamBlock

// repeated .protobuf.ShaderParam params = 1;
inline int ShaderParamBlock::params_size() const {
  return params_.size();
}
inline void ShaderParamBlock::clear_params() {
  params_.Clear();
}
inline const ::protobuf::ShaderParam& ShaderParamBlock::params(int index) const {
  return params_.Get(index);
}
inline ::protobuf::ShaderParam* ShaderParamBlock::mutable_params(int index) {
  return params_.Mutable(index);
}
inline ::protobuf::ShaderParam* ShaderParamBlock::add_params() {
  return params_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderParam >&
ShaderParamBlock::params() const {
  return params_;
}
inline ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderParam >*
ShaderParamBlock::mutable_params() {
  return &params_;
}

// optional string name = 2;
inline bool ShaderParamBlock::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShaderParamBlock::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShaderParamBlock::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShaderParamBlock::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& ShaderParamBlock::name() const {
  return *name_;
}
inline void ShaderParamBlock::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ShaderParamBlock::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void ShaderParamBlock::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShaderParamBlock::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* ShaderParamBlock::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShaderParamBlock::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ShaderProgram_Shader

// required .protobuf.ShaderProgram.ShaderType type = 1;
inline bool ShaderProgram_Shader::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ShaderProgram_Shader::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ShaderProgram_Shader::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ShaderProgram_Shader::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::protobuf::ShaderProgram_ShaderType ShaderProgram_Shader::type() const {
  return static_cast< ::protobuf::ShaderProgram_ShaderType >(type_);
}
inline void ShaderProgram_Shader::set_type(::protobuf::ShaderProgram_ShaderType value) {
  assert(::protobuf::ShaderProgram_ShaderType_IsValid(value));
  set_has_type();
  type_ = value;
}

// required string filename = 2;
inline bool ShaderProgram_Shader::has_filename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShaderProgram_Shader::set_has_filename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShaderProgram_Shader::clear_has_filename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShaderProgram_Shader::clear_filename() {
  if (filename_ != &::google::protobuf::internal::kEmptyString) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& ShaderProgram_Shader::filename() const {
  return *filename_;
}
inline void ShaderProgram_Shader::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void ShaderProgram_Shader::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
}
inline void ShaderProgram_Shader::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ShaderProgram_Shader::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    filename_ = new ::std::string;
  }
  return filename_;
}
inline ::std::string* ShaderProgram_Shader::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ShaderProgram_Shader::set_allocated_filename(::std::string* filename) {
  if (filename_ != &::google::protobuf::internal::kEmptyString) {
    delete filename_;
  }
  if (filename) {
    set_has_filename();
    filename_ = filename;
  } else {
    clear_has_filename();
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ShaderProgram

// repeated .protobuf.ShaderProgram.Shader shaders = 1;
inline int ShaderProgram::shaders_size() const {
  return shaders_.size();
}
inline void ShaderProgram::clear_shaders() {
  shaders_.Clear();
}
inline const ::protobuf::ShaderProgram_Shader& ShaderProgram::shaders(int index) const {
  return shaders_.Get(index);
}
inline ::protobuf::ShaderProgram_Shader* ShaderProgram::mutable_shaders(int index) {
  return shaders_.Mutable(index);
}
inline ::protobuf::ShaderProgram_Shader* ShaderProgram::add_shaders() {
  return shaders_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderProgram_Shader >&
ShaderProgram::shaders() const {
  return shaders_;
}
inline ::google::protobuf::RepeatedPtrField< ::protobuf::ShaderProgram_Shader >*
ShaderProgram::mutable_shaders() {
  return &shaders_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::ShaderProgram_ShaderType>() {
  return ::protobuf::ShaderProgram_ShaderType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ShaderProgram_2eproto__INCLUDED
