// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Skeleton.proto

#ifndef PROTOBUF_Skeleton_2eproto__INCLUDED
#define PROTOBUF_Skeleton_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Skeleton_2eproto();
void protobuf_AssignDesc_Skeleton_2eproto();
void protobuf_ShutdownFile_Skeleton_2eproto();

class Joint;

// ===================================================================

class Joint : public ::google::protobuf::Message {
 public:
  Joint();
  virtual ~Joint();

  Joint(const Joint& from);

  inline Joint& operator=(const Joint& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Joint& default_instance();

  void Swap(Joint* other);

  // implements Message ----------------------------------------------

  Joint* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Joint& from);
  void MergeFrom(const Joint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .protobuf.Joint children = 1;
  inline int children_size() const;
  inline void clear_children();
  static const int kChildrenFieldNumber = 1;
  inline const ::protobuf::Joint& children(int index) const;
  inline ::protobuf::Joint* mutable_children(int index);
  inline ::protobuf::Joint* add_children();
  inline const ::google::protobuf::RepeatedPtrField< ::protobuf::Joint >&
      children() const;
  inline ::google::protobuf::RepeatedPtrField< ::protobuf::Joint >*
      mutable_children();

  // repeated float currpose_transform = 2 [packed = true];
  inline int currpose_transform_size() const;
  inline void clear_currpose_transform();
  static const int kCurrposeTransformFieldNumber = 2;
  inline float currpose_transform(int index) const;
  inline void set_currpose_transform(int index, float value);
  inline void add_currpose_transform(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      currpose_transform() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_currpose_transform();

  // repeated float bindpose_transform = 3 [packed = true];
  inline int bindpose_transform_size() const;
  inline void clear_bindpose_transform();
  static const int kBindposeTransformFieldNumber = 3;
  inline float bindpose_transform(int index) const;
  inline void set_bindpose_transform(int index, float value);
  inline void add_bindpose_transform(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      bindpose_transform() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_bindpose_transform();

  // @@protoc_insertion_point(class_scope:protobuf.Joint)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::protobuf::Joint > children_;
  ::google::protobuf::RepeatedField< float > currpose_transform_;
  mutable int _currpose_transform_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > bindpose_transform_;
  mutable int _bindpose_transform_cached_byte_size_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Skeleton_2eproto();
  friend void protobuf_AssignDesc_Skeleton_2eproto();
  friend void protobuf_ShutdownFile_Skeleton_2eproto();

  void InitAsDefaultInstance();
  static Joint* default_instance_;
};
// ===================================================================


// ===================================================================

// Joint

// repeated .protobuf.Joint children = 1;
inline int Joint::children_size() const {
  return children_.size();
}
inline void Joint::clear_children() {
  children_.Clear();
}
inline const ::protobuf::Joint& Joint::children(int index) const {
  return children_.Get(index);
}
inline ::protobuf::Joint* Joint::mutable_children(int index) {
  return children_.Mutable(index);
}
inline ::protobuf::Joint* Joint::add_children() {
  return children_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protobuf::Joint >&
Joint::children() const {
  return children_;
}
inline ::google::protobuf::RepeatedPtrField< ::protobuf::Joint >*
Joint::mutable_children() {
  return &children_;
}

// repeated float currpose_transform = 2 [packed = true];
inline int Joint::currpose_transform_size() const {
  return currpose_transform_.size();
}
inline void Joint::clear_currpose_transform() {
  currpose_transform_.Clear();
}
inline float Joint::currpose_transform(int index) const {
  return currpose_transform_.Get(index);
}
inline void Joint::set_currpose_transform(int index, float value) {
  currpose_transform_.Set(index, value);
}
inline void Joint::add_currpose_transform(float value) {
  currpose_transform_.Add(value);
}
inline const ::google::protobuf::RepeatedField< float >&
Joint::currpose_transform() const {
  return currpose_transform_;
}
inline ::google::protobuf::RepeatedField< float >*
Joint::mutable_currpose_transform() {
  return &currpose_transform_;
}

// repeated float bindpose_transform = 3 [packed = true];
inline int Joint::bindpose_transform_size() const {
  return bindpose_transform_.size();
}
inline void Joint::clear_bindpose_transform() {
  bindpose_transform_.Clear();
}
inline float Joint::bindpose_transform(int index) const {
  return bindpose_transform_.Get(index);
}
inline void Joint::set_bindpose_transform(int index, float value) {
  bindpose_transform_.Set(index, value);
}
inline void Joint::add_bindpose_transform(float value) {
  bindpose_transform_.Add(value);
}
inline const ::google::protobuf::RepeatedField< float >&
Joint::bindpose_transform() const {
  return bindpose_transform_;
}
inline ::google::protobuf::RepeatedField< float >*
Joint::mutable_bindpose_transform() {
  return &bindpose_transform_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Skeleton_2eproto__INCLUDED
