// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Types.proto

#ifndef PROTOBUF_Types_2eproto__INCLUDED
#define PROTOBUF_Types_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Types_2eproto();
void protobuf_AssignDesc_Types_2eproto();
void protobuf_ShutdownFile_Types_2eproto();

class vec3;

// ===================================================================

class vec3 : public ::google::protobuf::Message {
 public:
  vec3();
  virtual ~vec3();

  vec3(const vec3& from);

  inline vec3& operator=(const vec3& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const vec3& default_instance();

  void Swap(vec3* other);

  // implements Message ----------------------------------------------

  vec3* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const vec3& from);
  void MergeFrom(const vec3& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);

  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);

  // required float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);

  // @@protoc_insertion_point(class_scope:protobuf.vec3)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  float x_;
  float y_;
  float z_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_Types_2eproto();
  friend void protobuf_AssignDesc_Types_2eproto();
  friend void protobuf_ShutdownFile_Types_2eproto();

  void InitAsDefaultInstance();
  static vec3* default_instance_;
};
// ===================================================================


// ===================================================================

// vec3

// required float x = 1;
inline bool vec3::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void vec3::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void vec3::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void vec3::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float vec3::x() const {
  return x_;
}
inline void vec3::set_x(float value) {
  set_has_x();
  x_ = value;
}

// required float y = 2;
inline bool vec3::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void vec3::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void vec3::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void vec3::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float vec3::y() const {
  return y_;
}
inline void vec3::set_y(float value) {
  set_has_y();
  y_ = value;
}

// required float z = 3;
inline bool vec3::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void vec3::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void vec3::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void vec3::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float vec3::z() const {
  return z_;
}
inline void vec3::set_z(float value) {
  set_has_z();
  z_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Types_2eproto__INCLUDED
