# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Mesh.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import VertexDeclaration_pb2
import Skeleton_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Mesh.proto',
  package='protobuf',
  serialized_pb='\n\nMesh.proto\x12\x08protobuf\x1a\x17VertexDeclaration.proto\x1a\x0eSkeleton.proto\"7\n\x08Triangle\x12\r\n\x05vert1\x18\x01 \x02(\r\x12\r\n\x05vert2\x18\x02 \x02(\r\x12\r\n\x05vert3\x18\x03 \x02(\r\"\xc1\x01\n\x04Mesh\x12\x10\n\x08material\x18\x01 \x02(\t\x12\x10\n\x08textures\x18\x02 \x03(\t\x12\x34\n\x0fvertices_format\x18\x03 \x02(\x0b\x32\x1b.protobuf.VertexDeclaration\x12\x15\n\rvertices_data\x18\x04 \x02(\x0c\x12!\n\x08skeleton\x18\x05 \x02(\x0b\x32\x0f.protobuf.Joint\x12%\n\ttriangles\x18\x06 \x03(\x0b\x32\x12.protobuf.Triangle')




_TRIANGLE = _descriptor.Descriptor(
  name='Triangle',
  full_name='protobuf.Triangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vert1', full_name='protobuf.Triangle.vert1', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vert2', full_name='protobuf.Triangle.vert2', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vert3', full_name='protobuf.Triangle.vert3', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=120,
)


_MESH = _descriptor.Descriptor(
  name='Mesh',
  full_name='protobuf.Mesh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='material', full_name='protobuf.Mesh.material', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='textures', full_name='protobuf.Mesh.textures', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertices_format', full_name='protobuf.Mesh.vertices_format', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vertices_data', full_name='protobuf.Mesh.vertices_data', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skeleton', full_name='protobuf.Mesh.skeleton', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='triangles', full_name='protobuf.Mesh.triangles', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=123,
  serialized_end=316,
)

_MESH.fields_by_name['vertices_format'].message_type = VertexDeclaration_pb2._VERTEXDECLARATION
_MESH.fields_by_name['skeleton'].message_type = Skeleton_pb2._JOINT
_MESH.fields_by_name['triangles'].message_type = _TRIANGLE
DESCRIPTOR.message_types_by_name['Triangle'] = _TRIANGLE
DESCRIPTOR.message_types_by_name['Mesh'] = _MESH

class Triangle(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRIANGLE

  # @@protoc_insertion_point(class_scope:protobuf.Triangle)

class Mesh(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESH

  # @@protoc_insertion_point(class_scope:protobuf.Mesh)


# @@protoc_insertion_point(module_scope)
