# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Skeleton.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Skeleton.proto',
  package='protobuf',
  serialized_pb='\n\x0eSkeleton.proto\x12\x08protobuf\"j\n\x05Joint\x12!\n\x08\x63hildren\x18\x01 \x03(\x0b\x32\x0f.protobuf.Joint\x12\x1e\n\x12\x63urrpose_transform\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x1e\n\x12\x62indpose_transform\x18\x03 \x03(\x02\x42\x02\x10\x01')




_JOINT = _descriptor.Descriptor(
  name='Joint',
  full_name='protobuf.Joint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='children', full_name='protobuf.Joint.children', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currpose_transform', full_name='protobuf.Joint.currpose_transform', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='bindpose_transform', full_name='protobuf.Joint.bindpose_transform', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=134,
)

_JOINT.fields_by_name['children'].message_type = _JOINT
DESCRIPTOR.message_types_by_name['Joint'] = _JOINT

class Joint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _JOINT

  # @@protoc_insertion_point(class_scope:protobuf.Joint)


_JOINT.fields_by_name['currpose_transform'].has_options = True
_JOINT.fields_by_name['currpose_transform']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_JOINT.fields_by_name['bindpose_transform'].has_options = True
_JOINT.fields_by_name['bindpose_transform']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
